sequence_id: 1
vis_data_type: 'pointcloud'
use_fps: True
normalize_xyz: False
bc_channel: 9
hidden_channel: 256 #the hidden channel of xcorr
category_name: Car # [Car, Van, Pedestrian, Cyclist, All]
out_channel: 256 #the output channel of xcorr
k: 4
use_search_bc: False
use_search_feature: False
vote_channel: 256 #the channel for vote aggregation
num_proposal: 64
up_axis: [0,0,1]
reference_BB: previous_result
search_bb_scale: 1.25
search_bb_offset: 2
template_size: 512
search_size: 1024
model_bb_scale: 1.25
model_bb_offset: 0
degrees: True # use degrees or radians
preload_offset: -1

# testing config
reference_BB: previous_result
shape_aggregation: firstandprevious
use_z: True
limit_box: False
IoU_space: 3